In [10]:
import numpy as np
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [14]:
type(my_array)


numpy.ndarray

In [16]:
#2d array 
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]
my_2d_array = np.array(my_2d_list)
my_2d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
# np.zeros()
# np.random.random()
# np.arange
print(np.zeros((5,3)))
print(np.random.random((2,3)))
print(np.arange(-3,4))
print(np.arange(-3,4,3))
print(np.arange(4))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.71169106 0.77047152 0.68468334]
 [0.97634809 0.31761547 0.34268123]]
[-3 -2 -1  0  1  2  3]
[-3  0  3]
[0 1 2 3]


In [50]:
# 3d array
array_1_2d = [[1,2],[3,5]]
array_2_2d = [[4,5],[6,7]]
array_3_2d = [[7,8],[9,4]]
array_3d = [[array_1_2d,array_2_2d,array_3_2d]]
array_3d
array = np.array(array_1_2d)
array.shape

(2, 2)

In [58]:
array = np.array([[1,2],[3,4],[5,6]])
print(array.flatten())

[1 2 3 4 5 6]


In [74]:
array = np.array([[1,2],[3,4],[5,6]])
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])