In [4]:
import numpy as np 
one_to_five = np.arange(1,6)
one_to_five
mask = one_to_five%2 ==0
mask
one_to_five[mask]



array([2, 4])

In [5]:
# for 2d arrays
classroom_ids_and_sizes = np.array([[1,22],[2,21],[3,27],[4,26]])
# we have to print the ids for the even size 
# making a condition 
classroom_ids_and_sizes[:,0][classroom_ids_and_sizes[:,1]%2==0]

array([1, 4])

In [6]:
# np.where function 
classroom_ids_and_sizes = np.array([[1,22],[2,21],[3,27],[4,26]])
np.where(classroom_ids_and_sizes[:,1]%2==0)

(array([0, 3]),)

In [7]:
# finding number of met condition values and then replacing them 
one_to_five = np.arange(1,6)
np.where(one_to_five%2==0,'0',one_to_five)

array(['1', '0', '3', '0', '5'], dtype='<U21')