In [11]:
import numpy as np
array_1d = np.array([1,2,3,4,5,6,7])
print(array_1d[4])
# slicing 
print(array_1d[2:5])
print(array_1d[::-1])

5
[3 4 5]
[7 6 5 4 3 2 1]


In [25]:
# 2d array 
array_2d = np.array([[2,5,4],[3,8,1],[7,6,9]])
print(array_2d[2,1])
print(array_2d[2])
print(array_2d[:,1])
print(array_2d[1:3,1:3])
np.sort(array_2d,axis=1)

6
[7 6 9]
[5 8 6]
[[8 1]
 [6 9]]


array([[2, 4, 5],
       [1, 3, 8],
       [6, 7, 9]])