In [4]:
import numpy as np 
array = np.array([1,2,3,4,5,6])
array.dtype

dtype('int64')

In [5]:
array = np.array([1.25,2.35,3.45,4.55])
array.dtype

dtype('float64')

In [6]:
np.array(['introduction','to','numpy']).dtype

dtype('<U12')

In [9]:
# type conversion
array = np.array([[True,False],[True,True],[False,False]],dtype=np.bool_)
array.astype(np.int32)

array([[1, 0],
       [1, 1],
       [0, 0]], dtype=int32)

In [11]:
np.array([True,'boop',42,42.42])

array(['True', 'boop', '42', '42.42'], dtype='<U32')

In [12]:
np.array([20.5,40.25,True,False,True])

array([20.5 , 40.25,  1.  ,  0.  ,  1.  ])

In [13]:
np.array([10,20,30.25,40.45])

array([10.  , 20.  , 30.25, 40.45])