In [26]:
import numpy as np
import matplotlib.pyplot as plt
security_breaches = np.array([
    [0,2,1],
    [6,4,0],
    [2,3,1],
    [0,0,1],
    [2,2,0]])
security_breaches
print(security_breaches.sum())
print(security_breaches.sum(axis=0))
print(security_breaches.sum(axis=1))

24
[10 11  3]
[ 3 10  6  1  4]


In [27]:
print(security_breaches.min())
print(security_breaches.min(axis=1))
print(security_breaches.min(axis=0))

0
[0 0 1 0 0]
[0 0 0]


In [28]:
print(security_breaches.max())
print(security_breaches.max(axis=1))
print(security_breaches.max(axis=0))

6
[2 6 3 1 2]
[6 4 1]


In [29]:
print(security_breaches.mean())
print(security_breaches.mean(axis=1))
print(security_breaches.mean(axis=0))

1.6
[1.         3.33333333 2.         0.33333333 1.33333333]
[2.  2.2 0.6]


In [30]:
print(security_breaches.mean(axis=0,keepdims=True))

[[2.  2.2 0.6]]


In [31]:
print(security_breaches.cumsum())
print(security_breaches.cumsum(axis=0))
print(security_breaches.cumsum(axis=1))

[ 0  2  3  9 13 13 15 18 19 19 19 20 22 24 24]
[[ 0  2  1]
 [ 6  6  1]
 [ 8  9  2]
 [ 8  9  3]
 [10 11  3]]
[[ 0  2  3]
 [ 6 10 10]
 [ 2  5  6]
 [ 0  0  1]
 [ 2  4  4]]


In [44]:
cum_sums_by_client = security_breaches.cumsum()
plt.plot(np.arange(1,6),cum_sums_by_client[:,0].cumsum(axis=0),label='client_1')
plt.plot(np.arange(1,6),cum_sums_by_client.mean(axis=1),label='average')
plt.legend()
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed