In [2]:
import numpy as np
array = np.array([
    [1,2,3],
    [4,5,6]
])
array + 3


array([[ 3,  6,  9],
       [12, 15, 18]])

In [3]:
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [4]:
array_2 = np.array([
    [0,1,0],
    [9,2,1]
])
array + array_2

array([[ 1,  3,  3],
       [13,  7,  7]])

In [5]:
array * array_2

array([[ 0,  2,  0],
       [36, 10,  6]])

In [9]:
array_2 > 1

array([[False, False, False],
       [ True,  True, False]])

In [11]:
string_array = np.array(['introduction','to','numpy'])
vectorized_len = np.vectorize(len)
vectorized_len(string_array)>2

array([ True, False,  True])